### ISSUE TITLE
Unable to configure `lifecycle_rules`

### ISSUE THREAD

**Issue by peterhirn** [Backblaze/terraform-provider-b2#65]
I'm trying to configure "Keep only the last version of the file" for a bucket via terraform.

```tf
resource "b2_bucket" "mail" {
  bucket_name = var.backblaze_bucket_name
  bucket_type = "allPrivate"

  lifecycle_rules {
    file_name_prefix              = ""
    days_from_hiding_to_deleting  = 1
  }
}
```

Result

```console
╷
│ Error: dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
│ Traceback (most recent call last):
│   File "b2_terraform/provider_tool.py", line 527, in run_command
│   File "b2_terraform/provider_tool.py", line 131, in run
│   File "b2_terraform/provider_tool.py", line 268, in resource_update
│   File "b2_terraform/provider_tool.py", line 303, in _preprocess
│ RuntimeError: default_retention can only be set if is_file_lock_enabled is true
```

## References
- https://github.com/Backblaze/terraform-provider-b2/issues/46

**Comment by vbaltrusaitis-reef** [comment]
Is that the exact Terraform configuration you've used when you encountered this error? I'm asking because:

1. I couldn't reproduce the issue, the bucket was created when I used identical configuration you provided.
2. The error you got (`RuntimeError: default_retention can only be set if is_file_lock_enabled is true`) is supposed to be triggered when you use `default_retention` field but don't set `is_file_lock_enabled` to true (Backblaze only supports `default_retention` with file lock feature enabled). And you're using neither of these fields here, looking at the code it doesn't look like this error could have been triggered without using `default_retention` field.

**Comment by peterhirn** [comment]
Thanks for trying to reproduce. Yes, this was the exact config.

Two things which might be necessary to trigger this:
- I run this on an existing bucket (maybe it only works when creating a new bucket)
- executed on Terraform Cloud (probably not relevant)

I'll test this again shortly and update this comment.

**Comment by vbaltrusaitis-reef** [comment]
Ah, indeed, I reproduced it by changing `days_from_hiding_to_deleting` and running `terraform apply` again. Looking into it.

**Comment by vbaltrusaitis-reef** [comment]
@peterhirn `v0.8.9` with a fix is released, it should appear in the Terraform Registry shortly.

Thank you for taking the time to report the issue!

**Comment by peterhirn** [comment]
Fix confirmed, works as expected. Thanks!
